export enum SessionType {
  TABLE_COLUMN = "TABLE_COLUMN",
  TABLE_ROW = "TABLE_ROW",
  CHART_PIE = "CHART_PIE",
  CHART_DONUT = "CHART_DONUT",
  CHART_HORIZONTAL_BAR = "CHART_HORIZONTAL_BAR",
  CHART_VERTICAL_BAR = "CHART_VERTICAL_BAR",
  CHART_TREEMAP = "CHART_TREEMAP"
}
